language: node_js
node_js:
  - "12"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - ng build
  - ng lint
  - ng test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
